#!/usr/bin/env python3.11
"""Generate smoker shard configs with explicit task ID lists.

Reads `task-site-mapping.json` + `test.raw.json` (WebArena truth files)
and emits:
  - config-smoker-shard-a.yaml  (shopping_admin + shopping)
  - config-smoker-shard-b.yaml  (reddit + gitlab)
  - data/smoker-task-ids.json   (reference, gitignored but regenerable)

Scope: ALL tasks in the 4 deployed apps. No eval-type filtering —
we include string_match, url_match, program_html, and their
combinations. No LLM-judge tasks exist in these 4 apps (verified).

Run:
    python3.11 scripts/smoker/generate-smoker-configs.py

This is idempotent. Re-run any time `test.raw.json` changes (e.g.
webarena package upgrade).
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from textwrap import dedent

REPO = Path(__file__).resolve().parents[2]
MAPPING_PATH = REPO / "task-site-mapping.json"
TEST_RAW_PATH = REPO / "test.raw.json"
TASK_IDS_OUT = REPO / "scripts" / "smoker" / "smoker-task-ids.json"
SHARD_A_OUT = REPO / "config-smoker-shard-a.yaml"
SHARD_B_OUT = REPO / "config-smoker-shard-b.yaml"

SHARD_A_APPS = ["ecommerce_admin", "ecommerce"]  # YAML app names
SHARD_B_APPS = ["reddit", "gitlab"]

# Map WebArena site label → YAML app key (they differ)
SITE_TO_APP = {
    "shopping_admin": "ecommerce_admin",
    "shopping": "ecommerce",
    "reddit": "reddit",
    "gitlab": "gitlab",
}


def load_task_ids() -> dict[str, list[int]]:
    """Return {yaml_app_name: [task_id, ...]} sorted ascending."""
    mapping = json.loads(MAPPING_PATH.read_text())
    test = json.loads(TEST_RAW_PATH.read_text())
    eval_map: dict[str, list[str]] = {
        str(t["task_id"]): t.get("eval", {}).get("eval_types", []) for t in test
    }

    per_app: dict[str, list[int]] = defaultdict(list)
    llm_skipped: dict[str, list[int]] = defaultdict(list)

    for tid_str, site in mapping.items():
        if site not in SITE_TO_APP:
            continue
        etypes = eval_map.get(tid_str, [])
        # Skip any LLM-judge tasks (need OPENAI_API_KEY; not guaranteed on EC2)
        if "llm_eval" in etypes or "string_match_llm_judge" in etypes:
            llm_skipped[SITE_TO_APP[site]].append(int(tid_str))
            continue
        per_app[SITE_TO_APP[site]].append(int(tid_str))

    for app in per_app:
        per_app[app].sort()

    if any(llm_skipped.values()):
        print("Skipped LLM-judge tasks:")
        for app, ids in llm_skipped.items():
            if ids:
                print(f"  {app}: {len(ids)} tasks ({ids[:3]}...)")
    else:
        print("No LLM-judge tasks in the 4 deployed apps (verified).")

    return per_app


def format_id_array(ids: list[int], per_line: int = 15) -> str:
    """Return flow-style YAML array with wrapping, indented 6 spaces."""
    chunks = [ids[i : i + per_line] for i in range(0, len(ids), per_line)]
    lines = [", ".join(f'"{i}"' for i in chunk) for chunk in chunks]
    indent = "      "
    joined = (",\n" + indent).join(lines)
    return f"[\n{indent}{joined}\n    ]"


def render_shard_config(shard_label: str, apps: list[str], ids: dict[str, list[int]]) -> str:
    total_tasks = sum(len(ids[a]) for a in apps)
    total_cases = total_tasks * 3  # 3 reps

    app_blocks = []
    task_blocks = []
    for app in apps:
        if app == "ecommerce":
            url = "http://10.0.1.50:7770"
        elif app == "ecommerce_admin":
            url = "http://10.0.1.50:7780"
        elif app == "reddit":
            url = "http://10.0.1.50:9999"
        elif app == "gitlab":
            url = "http://10.0.1.50:8023"
        else:
            raise ValueError(app)
        app_blocks.append(f"    {app}:\n      url: \"{url}\"")
        task_blocks.append(f"    {app}: {format_id_array(ids[app])}")

    apps_yaml = "\n".join(app_blocks)
    tasks_yaml = "\n".join(task_blocks)
    per_app_counts = "\n".join(f"#   {a}: {len(ids[a])} tasks" for a in apps)

    return dedent(f"""\
# Smoker Shard {shard_label} — Base solvability gate
# Generated by scripts/smoker/generate-smoker-configs.py
# Re-run that script if task-site-mapping.json or test.raw.json changes.
#
# Scope: ALL deployed-app tasks (no eval-type filter).
#   LLM-judge tasks are excluded (0 in these apps, verified).
#
{per_app_counts}
#   total: {total_tasks} tasks
#
# Matrix: {total_tasks} tasks × 1 base variant × 1 text-only agent × 3 reps
#       = {total_cases} cases
# Estimated: ~{total_cases * 12 // 60} min LLM time (~$150 at Claude Sonnet rates)
#
# Run on EC2:
#   nohup npx tsx scripts/runners/run-pilot3.ts \\
#     --config config-smoker-shard-{shard_label.lower()}.yaml \\
#     > smoker-shard-{shard_label.lower()}.log 2>&1 &
#
# Pre-run: reset WebArena Docker containers to ensure clean state.
# See docs/smoker-docker-reset.md.

webarena:
  apps:
{apps_yaml}

  tasksPerApp:
{tasks_yaml}

scanner:
  wcagLevels: ["A", "AA"]
  stabilityIntervalMs: 2000
  stabilityTimeoutMs: 15000
  concurrency: 1

variants:
  levels: ["base"]
  scoreRanges:
    base: {{ min: 0.40, max: 0.70 }}

runner:
  repetitions: 3
  maxSteps: 30
  concurrency: 1
  agentConfigs:
    - observationMode: "text-only"
      llmBackend: "claude-sonnet"
      maxSteps: 30
      retryCount: 3
      retryBackoffMs: 1000
      temperature: 0.0

recorder:
  waitAfterLoadMs: 10000
  concurrency: 1

output:
  dataDir: "./data/smoker-shard-{shard_label.lower()}"
  exportFormats: ["json", "csv"]
""")


def main() -> None:
    ids = load_task_ids()

    # Write reference JSON
    TASK_IDS_OUT.parent.mkdir(parents=True, exist_ok=True)
    out = {app: ids[app] for app in SHARD_A_APPS + SHARD_B_APPS}
    out["_meta"] = {
        "total": sum(len(v) for v in out.values()),
        "shard_a": {
            "apps": SHARD_A_APPS,
            "tasks": sum(len(ids[a]) for a in SHARD_A_APPS),
        },
        "shard_b": {
            "apps": SHARD_B_APPS,
            "tasks": sum(len(ids[a]) for a in SHARD_B_APPS),
        },
        "source": "test.raw.json + task-site-mapping.json",
        "eval_types_included": "all except llm_eval/string_match_llm_judge",
    }
    TASK_IDS_OUT.write_text(json.dumps(out, indent=2))
    print(f"Wrote {TASK_IDS_OUT}")

    # Write shard configs
    SHARD_A_OUT.write_text(render_shard_config("A", SHARD_A_APPS, ids))
    print(f"Wrote {SHARD_A_OUT} ({sum(len(ids[a]) for a in SHARD_A_APPS)} tasks)")

    SHARD_B_OUT.write_text(render_shard_config("B", SHARD_B_APPS, ids))
    print(f"Wrote {SHARD_B_OUT} ({sum(len(ids[a]) for a in SHARD_B_APPS)} tasks)")

    print("\nSummary:")
    for app in SHARD_A_APPS + SHARD_B_APPS:
        print(f"  {app}: {len(ids[app])} tasks")
    print(f"  TOTAL: {sum(len(ids[a]) for a in SHARD_A_APPS + SHARD_B_APPS)} tasks")


if __name__ == "__main__":
    main()
