#!/bin/bash
# =============================================================================
# deploy-burner.sh — Deploy infrastructure to a burner AWS account using
# Terraform workspaces for strict state isolation.
#
# Each burner account gets its own Terraform workspace + its own AWS CLI
# profile, so running this script against account A does NOT see account
# B's resources (and vice versa). No accidental cross-account destroys.
#
# Usage:
#   bash scripts/infra/deploy-burner.sh <ACCOUNT_ID> <PROFILE_NAME>
#
# Examples:
#   bash scripts/infra/deploy-burner.sh 946876341724 a11y-a
#   bash scripts/infra/deploy-burner.sh 904962391244 a11y-b
#
# Prerequisites:
#   1. mwinit (Midway login) — done once per session
#   2. ada credentials update for the target profile (done by this script if missing)
#   3. Bedrock model access enabled in that account's console (manual, AWS side)
# =============================================================================
set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Usage: $0 <ACCOUNT_ID> <PROFILE_NAME>"
    echo ""
    echo "Example: $0 946876341724 a11y-a"
    exit 1
fi

ACCOUNT_ID="$1"
PROFILE="$2"
WORKSPACE="burner-${ACCOUNT_ID}"
REGION="us-east-2"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
INFRA_DIR="$REPO_ROOT/infra"

echo "============================================"
echo " Burner Account Deploy"
echo "============================================"
echo "  Account:    $ACCOUNT_ID"
echo "  Profile:    $PROFILE"
echo "  Workspace:  $WORKSPACE"
echo "  Region:     $REGION"
echo ""

# ── Step 0: Refresh credentials via ada ──
echo "[0/6] Refreshing credentials via ada..."
if ! ada credentials update \
        --account="$ACCOUNT_ID" \
        --provider=conduit \
        --role=IibsAdminAccess-DO-NOT-DELETE \
        --once \
        --profile="$PROFILE" 2>&1 | tail -5; then
    echo "ERROR: ada credentials update failed. Have you run 'mwinit' today?"
    exit 1
fi

# Verify the profile resolves to the expected account
RESOLVED_ACCOUNT=$(aws sts get-caller-identity --profile "$PROFILE" --query Account --output text 2>&1)
if [ "$RESOLVED_ACCOUNT" != "$ACCOUNT_ID" ]; then
    echo "ERROR: Profile $PROFILE resolved to account $RESOLVED_ACCOUNT, expected $ACCOUNT_ID"
    exit 1
fi
echo "  ✓ Profile $PROFILE → account $RESOLVED_ACCOUNT"
echo ""

# ── Step 1: Terraform init (once; safe to re-run) ──
echo "[1/6] Terraform init..."
cd "$INFRA_DIR"
terraform init -input=false -no-color 2>&1 | tail -3
echo ""

# ── Step 2: Create or select workspace ──
echo "[2/6] Selecting Terraform workspace '$WORKSPACE'..."
if terraform workspace list 2>/dev/null | grep -qE "^\*?\s+${WORKSPACE}\$"; then
    terraform workspace select "$WORKSPACE"
    echo "  ✓ Selected existing workspace"
else
    terraform workspace new "$WORKSPACE"
    echo "  ✓ Created new workspace"
fi
echo ""

# ── Step 3: Terraform apply ──
echo "[3/6] Terraform apply (3-5 min — VPC, EC2s, IAM, S3)..."
terraform apply -auto-approve -input=false -no-color \
    -var="aws_profile=$PROFILE" \
    -var="aws_region=$REGION" \
    2>&1 | tail -20
echo ""

# ── Step 4: Capture outputs ──
echo "[4/6] Capturing deployment outputs..."
PLATFORM_ID=$(terraform output -raw instance_id)
WEBARENA_ID=$(terraform output -raw webarena_instance_id)
WEBARENA_IP=$(terraform output -raw webarena_private_ip)
S3_BUCKET=$(terraform output -raw s3_bucket_name)

echo "  Platform EC2:  $PLATFORM_ID"
echo "  WebArena EC2:  $WEBARENA_ID"
echo "  WebArena IP:   $WEBARENA_IP  (should be 10.0.1.50)"
echo "  S3 Bucket:     $S3_BUCKET"
echo ""

if [ "$WEBARENA_IP" != "10.0.1.50" ]; then
    echo "WARNING: WebArena IP is $WEBARENA_IP, expected 10.0.1.50"
    echo "Configs assume 10.0.1.50; update them or redeploy."
fi

# ── Step 5: Wait for SSM ──
echo "[5/6] Waiting for EC2s to register with SSM..."
for INSTANCE in "$PLATFORM_ID" "$WEBARENA_ID"; do
    echo -n "  $INSTANCE "
    for _ in $(seq 1 30); do
        STATUS=$(aws ssm describe-instance-information \
            --filters "Key=InstanceIds,Values=$INSTANCE" \
            --query "InstanceInformationList[0].PingStatus" \
            --output text --profile "$PROFILE" --region "$REGION" 2>/dev/null || echo "None")
        if [ "$STATUS" = "Online" ]; then
            echo "Online"
            break
        fi
        echo -n "."
        sleep 10
    done
    if [ "$STATUS" != "Online" ]; then
        echo " TIMEOUT (may need a few more minutes)"
    fi
done
echo ""

# ── Step 6: Save connection info ──
BURNER_INFO="$REPO_ROOT/data/burner-${PROFILE}.env"
mkdir -p "$(dirname "$BURNER_INFO")"
cat > "$BURNER_INFO" <<EOF
# Generated by deploy-burner.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
export BURNER_ACCOUNT=$ACCOUNT_ID
export AWS_PROFILE=$PROFILE
export AWS_REGION=$REGION
export PLATFORM_ID=$PLATFORM_ID
export WEBARENA_ID=$WEBARENA_ID
export WEBARENA_IP=$WEBARENA_IP
export S3_BUCKET=$S3_BUCKET
export TF_WORKSPACE=$WORKSPACE
EOF
echo "[6/6] Deployment complete"
echo "  Saved connection info: $BURNER_INFO"
echo ""
echo "  source $BURNER_INFO   # load into shell"
echo ""
echo "============================================"
echo " Next: bootstrap Platform EC2 + smoker launch"
echo "============================================"
echo ""
echo "  # Connect to Platform EC2:"
echo "  aws ssm start-session --target $PLATFORM_ID --region $REGION --profile $PROFILE"
echo ""
echo "  # On Platform EC2:"
echo "  sudo su - ec2-user"
echo "  export NVM_DIR=\"\$HOME/.nvm\" && . \"\$NVM_DIR/nvm.sh\""
echo "  cd ~/platform"
echo "  git pull"
echo "  ~/.local/bin/litellm --config litellm_config.yaml --port 4000 &"
echo ""
echo "  # Reset WebArena Docker (on the WebArena EC2):"
echo "  aws ssm start-session --target $WEBARENA_ID --region $REGION --profile $PROFILE"
echo "  for c in shopping shopping_admin forum gitlab; do docker restart \$c; done"
echo "============================================"
