#!/usr/bin/env bash
# Build paper-supplementary/ — a reviewer-facing bundle of derived analysis.
#
# Sources are the live results/ outputs (regenerable via `make verify-all` +
# `python3 analysis/{amt,stage3}_statistics.py`). The manually-curated parts
# (README.md, reproducibility-statement.md) are NOT touched here — they live
# in paper-supplementary/ directly and are git-tracked.
#
# Usage: bash scripts/maintenance/build-supplementary.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SUPP="$ROOT/paper-supplementary"
RESULTS="$ROOT/results"

cd "$ROOT"

echo "=== build-supplementary ==="
echo "ROOT:    $ROOT"
echo "TARGET:  $SUPP"
echo

# ── Statistics reports (Markdown) ────────────────────────────────
copy() {
  local src="$1"; local dst="$2"
  if [ -f "$src" ]; then
    cp "$src" "$dst"
    echo "  copied  $(basename "$src")  →  $(basename "$dst")"
  else
    echo "  MISSING $src — run upstream script first"
  fi
}

copy "$RESULTS/stats/full_report.md"            "$SUPP/statistics-composite.md"
copy "$RESULTS/amt/statistics_report.md"        "$SUPP/statistics-mode-a-c2.md"
copy "$RESULTS/stage3/statistics_report.md"     "$SUPP/statistics-stage3.md"
copy "$RESULTS/smoker/exclusion-report.md"      "$SUPP/exclusion-narrative.md"
copy "$RESULTS/amt/signature_alignment_report.md" "$SUPP/signature-alignment-report.md"

# ── Per-stage CSVs ───────────────────────────────────────────────
copy "$RESULTS/combined-experiment.csv"         "$SUPP/per-case-composite.csv"
copy "$RESULTS/stage3/per-operator-stage3.csv"  "$SUPP/per-operator-stage3.csv"
copy "$RESULTS/amt/dom_signature_matrix.csv"    "$SUPP/dom-signature-matrix.csv"
copy "$RESULTS/amt/behavioral_signature_matrix.csv" "$SUPP/behavioral-signature-matrix.csv"
copy "$RESULTS/amt/signature_alignment.csv"     "$SUPP/signature-alignment.csv"
copy "$RESULTS/bootstrap_decomposition.csv"     "$SUPP/bootstrap-decomposition.csv"
copy "$RESULTS/breslow_day_cross_model.txt"     "$SUPP/breslow-day-cross-model.txt"
copy "$RESULTS/glmm_model_comparison.csv"       "$SUPP/glmm-model-comparison.csv"
copy "$RESULTS/majority_vote_sensitivity.csv"   "$SUPP/majority-vote-sensitivity.csv"
copy "$RESULTS/stage3/visual-equiv/ssim-per-operator.csv" "$SUPP/ssim-per-operator.csv"
copy "$RESULTS/smoker/passing-tasks.json"       "$SUPP/smoker-passing-tasks.json"

# ── key-numbers.json (frozen at submission) ──────────────────────
copy "$RESULTS/key-numbers.json"                "$SUPP/key-numbers.json"

# ── Build manifest ───────────────────────────────────────────────
cat > "$SUPP/MANIFEST.txt" <<EOF
paper-supplementary bundle
generated by scripts/maintenance/build-supplementary.sh
date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

contents:
$(cd "$SUPP" && ls -1 | grep -v MANIFEST.txt)

regenerate: bash scripts/maintenance/build-supplementary.sh
upstream:   make verify-all && python3 analysis/amt_statistics.py && python3 analysis/stage3_statistics.py && python3 analysis/run_statistics.py
EOF

echo
echo "=== built $(ls "$SUPP" | wc -l | tr -d ' ') files in paper-supplementary/ ==="
