#!/usr/bin/env python3.11
"""
Figure F4: Behavioral Drop Bar Chart
=====================================

PURPOSE (paper §5.1):
  Show per-operator behavioral impact — the "damage ranking" of all 26 AMT
  operators. This is the first results figure readers encounter.

DESIGN RATIONALE:
  - Horizontal bar chart: operators on Y-axis (readable labels), drop on X-axis
  - Sorted by Claude text-only drop (primary signal, cleanest baseline)
  - Bars colored by operator family (L=red, ML=orange, H=green)
  - Llama 4 drops overlaid as diamond markers (cross-model replication)
  - H-baseline dashed vertical line shows the "no effect" reference
  - Key operators annotated with mechanism labels

WHY THIS DESIGN:
  - Horizontal bars allow long operator labels without rotation
  - Sorting by drop makes the "3-tier structure" visually obvious
  - Family coloring shows that destructive operators are all Low-family
  - Llama 4 overlay shows cross-model agreement without a separate figure
  - The gap between L1/L5 and everything else is the visual punchline

DATA SOURCE:
  results/amt/behavioral_signature_matrix.csv
  (generated by scripts/amt/amt-signature-analysis.py)

OUTPUT:
  figures/F4_behavioral_drop.png (300 DPI)
  figures/F4_behavioral_drop.pdf (vector)

USAGE:
  python3.11 figures/generate_F4_behavioral_drop.py
"""
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

# ── Config ──
plt.rcParams.update({
    'font.family': 'DejaVu Sans',
    'font.size': 8,
    'figure.dpi': 300,
    'axes.spines.top': False,
    'axes.spines.right': False,
})

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "results" / "amt" / "behavioral_signature_matrix.csv"
OUT = Path(__file__).resolve().parent

# ── Colors ──
COLORS = {'Low': '#C0392B', 'Midlow': '#E67E22', 'High': '#27AE60'}
LLAMA_COLOR = '#8E44AD'  # purple for Llama 4 markers
BASELINE_COLOR = '#2C3E50'

# ── Load data ──
df = pd.read_csv(DATA)
df['claude_text_drop_pp'] = df['claude_text_drop'] * 100
df['llama4_text_drop_pp'] = df['llama4_text_drop'] * 100

# Sort by Claude text-only drop (descending = most destructive at top)
df = df.sort_values('claude_text_drop_pp', ascending=True)

# ── Plot ──
fig, ax = plt.subplots(figsize=(7, 8))  # CHI double-column width

y_pos = np.arange(len(df))
bar_colors = [COLORS[fam] for fam in df['family']]

# Bars: Claude text-only drop
bars = ax.barh(y_pos, df['claude_text_drop_pp'], height=0.7,
               color=bar_colors, edgecolor='white', linewidth=0.3, alpha=0.85)

# Llama 4 markers (diamond)
ax.scatter(df['llama4_text_drop_pp'], y_pos, marker='D', s=25,
           color=LLAMA_COLOR, zorder=5, label='Llama 4 Maverick (text-only)')

# H-baseline reference line (0pp = H-operator average)
ax.axvline(x=0, color=BASELINE_COLOR, linestyle='--', linewidth=0.8, alpha=0.6)
ax.text(0.5, len(df) - 0.5, 'H-baseline\n(93.8%)', fontsize=7,
        color=BASELINE_COLOR, ha='left', va='top', style='italic')

# Y-axis labels: "L1 Landmark→div" format
labels = [f"{row['operator']}  {row['description']}" for _, row in df.iterrows()]
ax.set_yticks(y_pos)
ax.set_yticklabels(labels, fontsize=7)

# X-axis
ax.set_xlabel('Drop from H-baseline (percentage points)', fontsize=9)
ax.set_xlim(-10, 45)
ax.set_xticks([-10, 0, 10, 20, 30, 40])

# Title
ax.set_title('Per-Operator Behavioral Impact (Claude Text-Only, GT-Corrected)',
             fontsize=10, fontweight='bold', pad=12)

# Annotate key operators
for _, row in df.iterrows():
    if row['operator'] == 'L1':
        idx = df.index.get_loc(row.name)
        y = list(y_pos)[idx]
        ax.annotate('Landmark Paradox:\n6 DOM changes, −40pp',
                    xy=(row['claude_text_drop_pp'], y),
                    xytext=(row['claude_text_drop_pp'] - 5, y + 1.5),
                    fontsize=6.5, color='#C0392B', style='italic',
                    arrowprops=dict(arrowstyle='->', color='#C0392B', lw=0.8))
    elif row['operator'] == 'L5':
        idx = df.index.get_loc(row.name)
        y = list(y_pos)[idx]
        ax.annotate('Ghost Buttons:\nperception-action gap',
                    xy=(row['claude_text_drop_pp'], y),
                    xytext=(row['claude_text_drop_pp'] - 5, y + 1.5),
                    fontsize=6.5, color='#C0392B', style='italic',
                    arrowprops=dict(arrowstyle='->', color='#C0392B', lw=0.8))

# Legend
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
legend_elements = [
    Patch(facecolor=COLORS['Low'], label='Low family (L1–L13)'),
    Patch(facecolor=COLORS['Midlow'], label='Midlow family (ML1–ML3)'),
    Patch(facecolor=COLORS['High'], label='High family (H1–H8)'),
    Line2D([0], [0], marker='D', color='w', markerfacecolor=LLAMA_COLOR,
           markersize=6, label='Llama 4 Maverick'),
]
ax.legend(handles=legend_elements, loc='lower right', fontsize=7, framealpha=0.9)

# Tight layout
plt.tight_layout()

# Save
fig.savefig(OUT / "F4_behavioral_drop.png", dpi=300, bbox_inches='tight',
            facecolor='white', edgecolor='none')
fig.savefig(OUT / "F4_behavioral_drop.pdf", bbox_inches='tight',
            facecolor='white', edgecolor='none')
plt.close()

print(f"✅ F4 saved: {OUT / 'F4_behavioral_drop.png'}")
print(f"✅ F4 saved: {OUT / 'F4_behavioral_drop.pdf'}")
