/**
 * build-lib.ts — pure library for assembling the AMT `apply-all-individual.js`
 * build artefact from the 26 operator source files.
 *
 * This is the LIBRARY. The CLI is `scripts/build-operators.ts` — it's a
 * thin shell that calls `buildArtefact()` and writes the result to disk.
 *
 * Lives under `src/` (not `scripts/`) so it can be imported by tests
 * under the TypeScript rootDir without breaking `tsc` compilation.
 *
 * Contract (also documented in docs/amt-operator-spec.md):
 *   - Operators applied in CANONICAL ORDER (H → ML → L), regardless of
 *     the order in __OPERATOR_IDS at runtime.
 *   - Every Change record emitted by an operator is automatically tagged
 *     with operatorId by the generated wrapper.
 *   - Each operator body runs inside its own lexical { ... } block, so
 *     local const/let names don't collide across operators.
 *   - Unknown operator IDs in __OPERATOR_IDS silently skipped (lenient)
 *     unless __OPERATOR_STRICT === true (throws).
 *   - If __OPERATOR_IDS is empty or missing: default is to run NO
 *     operators (safe no-op).
 *
 * Determinism: run twice on a clean tree, `buildArtefact()` returns
 * byte-identical strings.
 */
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
// `src/variants/patches/` → repo root is three levels up.
const REPO_ROOT = join(__dirname, '../../..');

export const OPERATORS_DIR_PATH = join(REPO_ROOT, 'src/variants/patches/operators');
export const OUT_PATH_ABSOLUTE = join(REPO_ROOT, 'src/variants/patches/inject/apply-all-individual.js');

// Canonical application order. MUST match docs/amt-operator-spec.md §8.4.
// Order: H first (positive enhancement), ML (pseudo-compliance), L last
// (aggressive degradation). Rationale in spec §8.4.
export const OPERATOR_ORDER: readonly string[] = [
  'H1', 'H2', 'H3', 'H4', 'H5a', 'H5b', 'H5c', 'H6', 'H7', 'H8',
  'ML1', 'ML2', 'ML3',
  'L1', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9',
  'L10', 'L11', 'L12', 'L13',
] as const;

/**
 * Extract the body of an IIFE file. Strips the outer `(() => { ... })();`
 * wrapper and returns the inner statements as a string.
 *
 * Strategy: an operator file is required (by spec §2.1) to be a single
 * top-level IIFE. So we anchor on the FIRST `(() => {` from file start
 * and the LAST `})();` before EOF. Everything between them is the body.
 * We then check the body satisfies the §2.1 contract (declares
 * `const changes = []`, returns `changes`).
 *
 * This deliberately does NOT parse JS — it relies on the anchor
 * invariant. Anything clever inside the body (regex literals, template
 * strings, nested braces) is left alone.
 */
function extractIifeBody(source: string, operatorId: string): string {
  const stripped = source.trimEnd();

  const openAnchor = '(() => {';
  const closeAnchor = '})();';

  const openIdx = stripped.indexOf(openAnchor);
  if (openIdx === -1) {
    throw new Error(`[build-operators] ${operatorId}: missing '${openAnchor}' opening`);
  }
  const bodyStart = openIdx + openAnchor.length;

  const closeIdx = stripped.lastIndexOf(closeAnchor);
  if (closeIdx === -1 || closeIdx < bodyStart) {
    throw new Error(`[build-operators] ${operatorId}: missing '${closeAnchor}' closing`);
  }

  // Verify nothing non-trivial sits between `closeIdx + closeAnchor.length`
  // and EOF (a trailing newline or whitespace is OK).
  const tail = stripped.slice(closeIdx + closeAnchor.length).trim();
  if (tail.length > 0) {
    throw new Error(
      `[build-operators] ${operatorId}: content after closing ')();' — got '${tail.slice(0, 40)}'`
    );
  }

  const body = stripped.slice(bodyStart, closeIdx).trim();

  // Sanity assertions on body contents (per spec §2).
  if (!/\bconst\s+changes\s*=\s*\[\s*\]/.test(body)) {
    throw new Error(
      `[build-operators] ${operatorId}: body must declare 'const changes = []'`
    );
  }
  if (!/\breturn\s+changes\s*;?\s*$/.test(body)) {
    throw new Error(
      `[build-operators] ${operatorId}: body must end with 'return changes;'`
    );
  }

  return body;
}

export function buildArtefact(): string {
  const header = [
    '// AUTO-GENERATED by scripts/build-operators.ts — DO NOT EDIT BY HAND.',
    '// Regenerate with: npm run build:operators',
    '// Source: src/variants/patches/operators/*.js',
    '// Spec:   docs/amt-operator-spec.md',
    '//',
    '// Runtime protocol:',
    '//   window.__OPERATOR_IDS: string[]       — operators to apply, e.g. ["L3","H2"]',
    '//   window.__OPERATOR_STRICT: boolean     — throw on unknown IDs (default: false)',
    '// Returns: Change[] — each with operatorId auto-injected.',
    '',
  ].join('\n');

  const wrapperOpen = [
    '(() => {',
    '  const ids = Array.isArray(window.__OPERATOR_IDS) ? window.__OPERATOR_IDS : [];',
    '  const strict = window.__OPERATOR_STRICT === true;',
    '  const validIds = new Set([' +
      OPERATOR_ORDER.map(id => `'${id}'`).join(',') +
    ']);',
    '  if (strict) {',
    '    for (const id of ids) {',
    '      if (!validIds.has(id)) {',
    '        throw new Error("apply-all-individual: unknown operator id " + id);',
    '      }',
    '    }',
    '  }',
    '  const wanted = new Set(ids.filter(id => validIds.has(id)));',
    '  const should = (id) => wanted.has(id);',
    '  const allChanges = [];',
    '',
  ].join('\n');

  const blocks: string[] = [];
  for (const opId of OPERATOR_ORDER) {
    const sourcePath = join(OPERATORS_DIR_PATH, `${opId}.js`);
    if (!existsSync(sourcePath)) {
      throw new Error(`[build-operators] missing source: ${sourcePath}`);
    }
    const source = readFileSync(sourcePath, 'utf-8');
    const body = extractIifeBody(source, opId);
    // Indent body by 4 spaces for readability in the artefact.
    const indentedBody = body
      .split('\n')
      .map(line => (line.length > 0 ? '      ' + line : line))
      .join('\n');

    blocks.push([
      `  // ─── ${opId} ───`,
      `  if (should('${opId}')) {`,
      `    const _opChanges = (() => {`,
      indentedBody,
      `    })();`,
      `    for (const ch of _opChanges) {`,
      `      ch.operatorId = '${opId}';`,
      `      allChanges.push(ch);`,
      `    }`,
      `  }`,
      '',
    ].join('\n'));
  }

  const wrapperClose = [
    '  return allChanges;',
    '})();',
    '',
  ].join('\n');

  return header + wrapperOpen + blocks.join('') + wrapperClose;
}
