#!/usr/bin/env python3
"""
Smoke tests for _build_variant_js in browsergym_bridge.py.

These are static-string tests — they verify that the JS the bridge
assembles has the right shape. They do NOT run the JS (that requires
Playwright + a real browser, covered by the TS-side integration tests
in src/variants/patches/operators/operators.test.ts).

Run: python3 src/runner/test_build_variant_js.py
"""
import json
import sys
from pathlib import Path

# Import the function under test without running main()
sys.path.insert(0, str(Path(__file__).parent))

# Minimal import-safe path: read + parse the module, extract just what
# we need. browsergym_bridge imports gymnasium/browsergym at top level
# which aren't available in a bare Python shell, so we load the module
# source and compile _build_variant_js + VARIANT_SCRIPTS + INJECT_DIR
# only.
import ast
import pathlib as _pl
SOURCE = (Path(__file__).parent / 'browsergym_bridge.py').read_text(encoding='utf-8')
tree = ast.parse(SOURCE)

# Whitelist the bindings we want
WANTED = {
    'INJECT_DIR', 'VARIANT_SCRIPTS', '_build_variant_js',
}
stripped_body = []
for node in tree.body:
    keep = False
    if isinstance(node, ast.Assign):
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id in WANTED:
                keep = True
    elif isinstance(node, ast.FunctionDef) and node.name in WANTED:
        keep = True
    elif isinstance(node, ast.ImportFrom):
        # keep relevant imports only
        if node.module in ('json', 'pathlib', 'sys'):
            keep = True
    elif isinstance(node, ast.Import):
        for alias in node.names:
            if alias.name in ('json', 'pathlib', 'sys'):
                keep = True
                break
    if keep:
        stripped_body.append(node)
stripped_tree = ast.Module(body=stripped_body, type_ignores=[])
namespace: dict = {'__file__': str(Path(__file__).parent / 'browsergym_bridge.py'),
                   '__name__': 'bridge_test_shim'}
exec(compile(stripped_tree, 'browsergym_bridge.py', 'exec'), namespace)
_build_variant_js = namespace['_build_variant_js']

FAILED = 0


def expect(condition, msg):
    global FAILED
    if not condition:
        print(f'  FAIL: {msg}', file=sys.stderr)
        FAILED += 1
    else:
        print(f'  ok: {msg}')


# Test 1: base returns None
print('Test: base variant returns None (no-op signal)')
expect(_build_variant_js('base', {}) is None, 'base -> None')

# Test 2: legacy variants return the raw JS file
print('Test: low variant returns apply-low.js contents unchanged')
low_js = _build_variant_js('low', {})
expect(low_js is not None and 'apply-low.js block 1' in low_js or 'semanticTags' in low_js,
       'low includes expected apply-low.js body tokens')
expect('__OPERATOR_IDS' not in low_js, 'low does NOT include operator preamble')

# Test 3: individual without operatorIds returns None with warning
print('Test: individual without operatorIds returns None (safe no-op)')
indiv_empty = _build_variant_js('individual', {})
expect(indiv_empty is None, 'individual without operatorIds -> None')
indiv_wrong = _build_variant_js('individual', {'operatorIds': []})
expect(indiv_wrong is None, 'individual with empty operatorIds -> None')
indiv_wrong2 = _build_variant_js('individual', {'operatorIds': 'L3'})  # not a list
expect(indiv_wrong2 is None, 'individual with non-list operatorIds -> None')

# Test 4: individual with valid IDs has preamble and the IIFE
print('Test: individual with operatorIds has correct shape')
indiv = _build_variant_js('individual', {'operatorIds': ['L3']})
expect(indiv is not None, 'individual with valid IDs -> string')
expect('window.__OPERATOR_IDS = ["L3"]' in indiv, 'preamble contains exact ID literal')
expect('window.__OPERATOR_STRICT = true' in indiv, 'strict mode enabled')
expect('AUTO-GENERATED by scripts/amt/build-operators.ts' in indiv,
       'body is apply-all-individual.js')
# Preamble MUST come BEFORE the IIFE (otherwise globals unset when IIFE reads them)
preamble_idx = indiv.find('__OPERATOR_IDS')
iife_idx = indiv.find('(() => {')
expect(preamble_idx < iife_idx, 'preamble precedes IIFE (order matters for globals)')

# Test 5: multiple operator IDs
print('Test: individual with composition (multiple IDs)')
indiv_multi = _build_variant_js('individual', {'operatorIds': ['L3', 'H2']})
expect('["L3", "H2"]' in indiv_multi or '"L3","H2"' in indiv_multi,
       'both IDs present in preamble')

# Test 6: unknown variant_level returns None
print('Test: unknown variant_level returns None')
expect(_build_variant_js('nonsense', {}) is None,
       'nonsense level -> None')

print('')
if FAILED > 0:
    print(f'FAILED: {FAILED} assertion(s)', file=sys.stderr)
    sys.exit(1)
print(f'PASSED: all assertions')
